- name : Configure Docker on EC2 Instances
  hosts : testserver
  become: true
  connection : ssh
  tasks : 
  - name: updating apt
    command : sudo apt-get update

  - name : Install Docker
    command : sudo apt-get install -y docker.io

  - name : Start Docker Service
    command : sudo systemctl start docker

  - name: Deploy Docker Container
    command: docker run -td -p 8084:8081 sandeepajay1/finance-me:1.0
